### ISSUE TITLE
start_advertising() got an unexpected keyword argument 'timeout'

### ISSUE THREAD

**Issue by sandhu0409** [adafruit/Adafruit_CircuitPython_BLE#112]
I have run ble_uart_echo_test.py and got this error
```
Traceback (most recent call last):
  File "echoTest.py", line 10, in <module>
    ble.start_advertising(advertisement)
  File "/usr/local/lib/python3.7/dist-packages/adafruit_ble/__init__.py", line 212, in start_advertising
    timeout=0 if timeout is None else timeout,
TypeError: start_advertising() got an unexpected keyword argument 'timeout'
```

**Comment by dhalbert** [comment]
This was "fixed" by https://github.com/adafruit/Adafruit_Blinka_bleio/pull/26, so you need to update your local copy of `adafruit-blinka-bleio":
```
pip3 install --upgrade adafruit-blinka-bleio
```
However, `adafruit-blinka-bleio` does not support advertising, because it supports acting only as a BLE central, not a peripheral. So you will still get an error when you run this, just a more informative one. This is a limitation of the underlying library, `bleak`, that we use for multiplatform BLE support.
