### ISSUE TITLE
Advertisements aren't including name

### ISSUE THREAD

**Issue by dhalbert** [adafruit/Adafruit_CircuitPython_BLE#35]
The various advertisement classes, including `ProvideServicesAdvertisement`, etc. are not including a name in the advertising packet or scan response. This means that when the devices first appear in a list, say, to connect or pair to, just the address is listed. Once the peer caches the name, it will it will show up in lists, but the name should be included in the advertisement and/or scan response.

@tannewt: in https://circuitpython.readthedocs.io/en/latest/shared-bindings/_bleio/Adapter.html#_bleio.Adapter.name, it says:

>**name:** name of the BLE adapter used once connected. Not used in advertisements. The name is “CIRCUITPY” + the last four hex digits of adapter.address, to make it easy to distinguish multiple CircuitPython boards.

I think you added the  "Not used in advertisements". Normally I would expect this name would be used as the default advertisement name.

**Comment by tannewt** [comment]
As is, names are included when they are set. I didn't want to have a default because it impacts the length of the advertisement packet implicitly.

We chatted about this and decided it be best to provide a default scan response when one isn't provided. It's common to place the name and tx power in the scan response because the values are fixed and not changing often. Providing a default scan response also alleviates the worry of fitting default data and user provided data together in one advertisement.
